services:
  web:
    # start with `docker-compose --profile local up`
    build:
      context: .
      args:
        - VERSION=local
      ports:
        - "8083:80"
    volumes:
      - ./config:/config

  gotify:
    image: gotify/server
    ports:
      - "8085:80"
    volumes:
      - ./data/gotify/data:/app/data
