name: Generate Docs

on:
  push:
    paths:
      - docs/**
      - .github/workflows/docs.yaml
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.147.7"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - run: |
          cd docs
          npm i
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          publish_branch: docs
